#!/bin/bash
#ifs.sh

# Inspect - inspect and reject files - Rowland Cheshire December 2017
# cheshire_r@fastmail.fm

# Inspect and reject files
# GPLv3 - distribute as desired - not for commercial use - attribution rights.

# Acknowledgements
# Ivo Jaeger (http://siliconfields.net)
# dcraw: (http://www.cybercom.net/~dcoffin/)
# ImageMagick: (http://www.imagemagick.org/script/index.php)

# location of Asterism source files

	if [ -e /usr/local/bin/asterism ]; then
	source=$(readlink -f /usr/local/bin); else
	source=$(pwd)
	fi

# no at bridge	

	export NO_AT_BRIDGE=1

# title
	title='Inspect'

# location of yad window icon

	if [ -e /usr/local/bin/AsterismLOGOs.png ]; then
	wicon=$(readlink -f /usr/local/bin/AsterismLOGOs.png); else
	wicon=$(readlink -f $source/AsterismLOGOs.png)
fi

# create directory (if needed) helper function
	function createDirIfNeeded ()
	{
	if [ -d $1 ]
	then
		echo " " >/dev/null 2>&1
	else
		echo "		Creating $1 folder"
	mkdir $1
	fi
	}

# yad progress function
	function yadProgress ()
	{
	yad --progress --center \
  		--title="$title" \
		--progress-text="$text" \
		--window-icon=$wicon \
		--width=300 \
		--pulsate \
		--no-buttons \
  		--auto-close \
  		--auto-kill 2>/dev/null
	}

# file type function
	function fileType () 
	{
	FILES=$(basename -a *.*)
	ext="${FILES##*.}"
	}

# yad error function
	function yadError ()
	{
	(( $? != 0 )) && yad --error --text="Error in yad command"
	}

# killall function
	function killAll ()
	{
	killall inspector awk
	}

# location of inspector log

	log=~/.asterism/preview_log

# select image files
	text=$(echo "Select image files")
	
	IFS=$'\n'
	files=($(yad --file-selection --center --window-icon=$wicon --height=600 --width=480 --title="$title - select image files" --text="Select images" --button=Skip:1 --button=Select:0 --multiple --separator=$'\n' 2>/dev/null))
	echo "${files[@]}"

	imagedir=`echo "$files" |xargs dirname`
	echo $imagedir

	previewdir=$imagedir/.preview
	rejectdir=$imagedir/rejects

	yad --width=350 --window-icon=$wicon --title="$title" \
		--text="<b>Inspect variables</b> " \
		--form \
		--button=Quit:1 \
		--button=Inspect:0 \
		--separator=":" \
		--field="Preview size":SCL \
			'40!0..100!0' \
		--field="RAW files":CHK \
			'TRUE!FALSE' \
		--field="Remove previews":CHK \
			'TRUE!FALSE' | awk 'BEGIN { FS = ":" } ; { print $0 }' > $log 
	
# run quit inspector
	if [[ $? = 1 || $? = 252 ]]; then
	killAll
	exit 1; else
	echo " " >/dev/null 2>&1
	fi
	
	preview=$(awk 'BEGIN { FS = ":" } ; { print $1 }' preview=$1 $log)
	raw=$(awk 'BEGIN { FS = ":" } ; { print $2 }' raw=$2 $log)
	remove=$(awk 'BEGIN { FS = ":" } ; { print $3 }' remove=$3 $log)
	

	echo "		RAW $raw
		Preview size $preview
		Remove previews $remove
	"
	cd $previewdir

	f=$(find . -maxdepth 1 -type f | wc -l)

	if [ -e "$previewdir" ] && [ "$f" > "0" ] && [ "$remove" != "TRUE" ]; then
	echo " " >/dev/null 2>&1; else

	if [ "$remove" != "TRUE" ]; then
	echo "		Keep previews"
	echo " " >/dev/null 2>&1; else
	echo "		Remove previews"
	rm -f -R $previewdir
	fi
fi
	createDirIfNeeded $previewdir
	createDirIfNeeded $rejectdir

	cd $imagedir

	echo "		Inspect - generate previews"

	if [ "$raw" != "TRUE" ]; then
	echo " " >/dev/null 2>&1; else

	text=$(echo "Generating previews - please wait...")
	(
	echo ""

	for i in `ls -v ${files[@]}`;do dcraw -o 0 -t 0 -w -h $i; mogrify -auto-gamma -resize $preview% -format jpg *.ppm; mv *.jpg $previewdir; rm -f *.ppm;done	
	) |
	yadProgress
	yadError
fi
	if [ "$raw" = "TRUE" ]; then
	echo " " >/dev/null 2>&1; else

	text=$(echo "Generating previews - please wait...")
	(
	echo ""

	fileType

	for i in `ls -v ${files[@]}`;do mogrify -auto-gamma -normalize -resize $preview% -format jpg *.$ext ; mv *.jpg $previewdir;done
	) |
	yadProgress	
	yadError
fi

	cd $imagedir

	text=$(echo "Move image files to reject folder")

	for i in $previewdir/*.jpg;do mv -- "$i" "${i%%.jpg}";done

	animate -delay 50 -loop 0 $previewdir/* |
	(
	IFS=$'\n'
	files=($(yad --file-selection --window-icon=$wicon --height=680 --width=480 --title="$title" --text="Move image files to reject folder" --multiple --button=Skip:1 --button=Proceed:0 --separator=$'\n' 2>/dev/null))
	mv "${files[@]}" "$rejectdir" 2>/dev/null
	) |
	yadProgress
	yadError

# Leave Inspect

	text=$(echo "Leave Inspect")

	yad --progress --center \
  	--title="$title" \
	--progress-text="$text" \
	--window-icon=$wicon \
	--width=300 \
	--pulsate \
	--no-buttons \
  	--timeout=2 2>/dev/null

	echo "		Leave Inspect"

	killAll

exit
